<a href="https://colab.research.google.com/github/llizima/NCF_Algorithms/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Understanding Data Types in Python**

Exercise 1

Problem:

Explain the difference between a Python list and a NumPy array in terms of data types and performance.

#solution goes here

Exercise 2

Problem:

Given the list L = [1, 2, 3, 4, 5], convert it to a NumPy array of type float.

In [ ]:
#solution goes here

import numpy as np
L = [1, 2, 3, 4, 5]

np.array(L, dtype = float)

array([1., 2., 3., 4., 5.])

Exercise 3

Problem:

Create a NumPy array of size 10 filled with zeros, ensuring the data type is integer.

In [ ]:
#solution goes here


array([-10])

**The Basics of NumPy Arrays**

Exercise 1

Problem:

Create a 3×3 NumPy array with values ranging from 0 to 8.

Exercise 2

Problem:

Given the array a = np.array([1, 2, 3, 4, 5]), access the third element and change its value to 10.

Exercise 3

Problem:

Create a 2D NumPy array of shape (2, 5) with random integers between 0 and 10.

In [ ]:
#solutions go here
import numpy as np
temp = np.arange(9).reshape(3, 3)
print(temp)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
np.arange(5)/np.arange(1, 6)


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x = np.arange(4)
x


array([0, 1, 2, 3])

In [ ]:
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
theta = np.linspace(0, np.pi, 10)

In [ ]:
theta

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

**Computation on NumPy Arrays: Universal Functions**

Exercise 1

Problem:

Given two arrays x = np.array([1, 2, 3, 4]) and y = np.array([5, 6, 7, 8]), compute the element-wise sum and product.

Exercise 2

Problem:

Apply the exponential function to the array x = np.array([1, 2, 3, 4]).

Exercise 3

Problem:

Compute the sine of x = np.array([1, 2, 3, 4]) and cosine of y = np.array([5, 6, 7, 8]), then find the sum of their squares.

In [ ]:
#solutions go here
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

sum_array = x + y
product_array = x * y

print("Sum:", sum_array)
print("Product:", product_array)


Sum: [ 6  8 10 12]
Product: [ 5 12 21 32]


In [ ]:
x = np.array([1, 2, 3, 4])
exp_array = np.exp(x)
print(exp_array)


[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

sin_x = np.sin(x)
cos_y = np.cos(y)
sum_squares = sin_x**2 + cos_y**2

print("Sum of squares:", sum_squares)

Sum of squares: [0.78853765 1.74874879 0.58828347 0.59392028]


**Aggregations: Min, Max, and Everything In Between**

Exercise 1

Problem:

Given data = np.random.rand(100), compute the mean, median, and standard deviation.

Exercise 2

Problem:

Create a 5×5 matrix with random integers from 1 to 100. Find the maximum and minimum values along the rows and columns.

Exercise 3

Problem:

Given data = np.arange(1, 11), compute the cumulative sum and cumulative product.

In [ ]:
#solution goes here

**Computation on Arrays: Broadcasting**

Exercise 1

Problem:

Add the vector v = np.array([1, 2, 3]) to each row of the 3×3 matrix:

python
Copy code
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
Exercise 2

Problem:

Multiply a 4×1 vector by a 1×3 vector to get a 4×3 matrix.

Exercise 3

Problem:

Subtract the mean of each column from the respective column elements in a 3×3 matrix.

In [ ]:
#solutions go here

**Comparisons, Masks, and Boolean Logic**

Exercise 1

Problem:

Given data = np.random.randint(0, 20, size=15), find all elements greater than 10.

Exercise 2

Problem:

Create an array of numbers from 1 to 20. Replace all even numbers with zero.

Exercise 3

Problem:

Given x = np.array([1, 2, 3, 4, 5]) and y = np.array([5, 4, 3, 2, 1]), find the positions where x is less than y.

In [ ]:
#solutions go here

**Fancy Indexing**

Exercise 1

Problem:

Given x = np.array([10, 20, 30, 40, 50, 60]) and indices = [1, 3, 5], use fancy indexing to extract elements at the given indices.

Exercise 2

Problem:

Given a 4×4 array, select the diagonal elements using fancy indexing.

Exercise 3

Problem:

Given x = np.arange(10), shuffle the array using fancy indexing.

In [ ]:
#solutions go here

**Sorting Arrays**

Exercise 1

Problem:

Sort the array x = np.array([3, 6, 2, 7, 1, 9]) in ascending and descending order.

Exercise 2

Problem:

Given a 2D array array_2d = np.random.randint(0, 10, size=(3, 5)), sort each row.

Exercise 3

Problem:

Given names = np.array(['John', 'Anne', 'Zoe', 'Bob']) and ages = np.array([25, 30, 22, 28]), sort the names array based on the ages array.



In [ ]:
#solution goes here

**Structured Data: NumPy's Structured Arrays**

Exercise 1

Problem:

Create a structured array to store the names and ages of people.

Exercise 2

Problem:

Access the 'age' field of the structured array created above.

Exercise 3

Problem:

Given the structured array:

python
Copy code
students = np.array([('Alice', 25, 85.5), ('Bob', 30, 92.3), ('Cathy', 28, 78.9)],
                    dtype=[('name', 'U10'), ('age', 'i4'), ('score', 'f4')])
Find the average score.

In [ ]:
#solutions go here

In [ ]:
import numpy as np


In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [2]:
import numpy as np

nums = [3,2,4]
target = 6

vec_targ = np.full((len(nums)),target)
ntarget = vec_targ - nums
print(ntarget)
def twoSum(nums, target):
  vec_targ = np.full((len(nums)),target)
  ntarget = vec_targ = np.full((len(nums)),target) - nums


[3 4 2]
